config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :categories, only: [:new, :create, :index, :edit, :update]
  # get 'home/index'
  # get 'home', to: 'home#index'

  root to: "home#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :categories
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user  # Assuming you have a current_user method from Devise or similar

    begin
      if @category.save
        # redirect_to some_path, notice: 'Category was successfully created.'
        redirect_to categories_path, notice: "Category was successfully created."
      else
        render :new
      end
    rescue ActiveRecord::RecordNotUnique
      @category.errors.add(:name, "has already been taken")
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
    def index
      render
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/edit.html.erb
<div class="title-page">
  <span>
    <i class="fa-solid fa-pencil-alt icon-title"></i>
  </span>
  <span class="header-page_title">
    Επεξεργασία Κατηγορίας
  </span>
</div>
<div class="container mt-3">
  <%= form_with(model: @category, local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being updated:</h2>
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, id: :category_name, class: 'form-control', required: true %>
      <div class="invalid-feedback">
        Please provide a valid category name.
      </div>
    </div>
    <div class="actions">
      <%= form.submit 'Update Category', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="title-page">
  <span>
    <i class="fa-solid fa-list icon-title"></i>
  </span>
  <span class="header-page_title">
    Λίστα Κατηγοριών
  </span>
</div>
<div class="container mt-3">
  <table class="table table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.name %></td>
          <td>
            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-sm btn-primary' %>
            <%# link_to 'Delete', category_path(category),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<div class="title-page">
  <span>
    <i class="fa-solid fa-plus icon-title"></i>
  </span>
  <span class="header-page_title">
    Δημιουργία Κατηγορίας
  </span>
</div>
<div class="container mt-3">
  <%= form_with(model: @category, local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, id: :category_name, class: 'form-control', required: true %>
      <div class="invalid-feedback">
        Please provide a valid category name.
      </div>
    </div>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div> Welcome <%= current_user.email %> </div>
<% else %>
  <%= button_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/_sidebar.html.erb
<%
=begin%>
<div class="sidebar">
  <ul>
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>
<%
=end%>
<div id="custombody" class="sb-nav-fixed">
  <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <%
=begin%>
    <img class=" navbar-brand ps-3 logo_skroutzaa" src="https://c.scdn.gr/assets/schwartz/logo-4636919242747e42156835b0b8673b0c.svg" alt="Skroutz Logo" />
    <%
=end%>
    <a class="navbar-brand ps-3" routerLink="/homepage">
      <img class="logo_skroutz" src="https://c.scdn.gr/assets/schwartz/logo-4636919242747e42156835b0b8673b0c.svg" alt="Skroutz Logo" />
    </a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
                class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
      <div class="input-group">
        <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..."
                    aria-describedby="btnNavbarSearch" />
        <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i
                        class="fas fa-search"></i></button>
      </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%
=begin%>
          <li><a class="dropdown-item" style="cursor:pointer" id="logout-btn">Logout</a></li>
          <%
=end%>
          <li>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
  <div id="layoutSidenav">
    <div id="layoutSidenav_nav">
      <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
          <div class="nav">
            <!-- categories start -->
            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                            data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
              <div class="sb-nav-link-icon"><i class="side-icon  fa-solid fa-box" style="color: #1465f0;"></i></div>
              Κατηγορίες
              <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                            data-bs-parent="#sidenavAccordion">
              <nav class="sb-sidenav-menu-nested nav">
                <a class="nav-link" href="<%= new_category_path %>">Δημιουργία</a>
                <a class="nav-link" href="<%= categories_path %>">Λίστα</a>
              </nav>
            </div>
            <!-- categories end -->
          </div>
        </div>
        <div class="sb-sidenav-footer">
          <div class="small">Logged in as: <%= current_user.email %></div>
        </div>
      </nav>
    </div>
    <div id="layoutSidenav_content">
      <!-- main start -->
      <div class="main">
        <%= yield %>
      </div>
      <!-- main end -->
      <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
          <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Skroutz</div>
          </div>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <script type="module">
      import "sidebar"
    </script>
    <% if devise_controller? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    <% else %>
      <!-- Render the sidebar for non-Devise controllers -->
      <%= render 'layouts/sidebar' %>
    <% end %>
  </body>
</html>